### ISSUE TITLE
Error "wrong number"

### ISSUE THREAD

**Issue by developerfranso** [PhoneGuardian/CitizenApp#1]
the app is running well but when you try to register it says that the number u entered is wrong..what might be the promblem

**Comment by mirjamsk** [comment]
Does the country code correspond to the one your sim card uses?

**Comment by developerfranso** [comment]
okay thanks for ur responce  i have been using android emulator but i have tried with my phone and it works though im unable to save image captured

**Comment by mirjamsk** [comment]
At this point we have decided to scrape that feature. Have you pulled the
latest version of the pp? In that version there is no image capture
possibility

**Comment by developerfranso** [comment]
hello yeah i have pulled the new app but the photo was making it cool does
it have a db or something on where it can stor e data

**Comment by mirjamsk** [comment]
that's useful input, thank you.
and yes, it does use/have a database, only the code is not publicly available at this moment becasuse of security reasons.

**Comment by developerfranso** [comment]
ok yeah i have a  db. would you kindly help me with those codes im
developing a crime reporting app for my 2nd year study. i would appreciate
